### ISSUE TITLE
How to use？

### ISSUE THREAD

**Issue by wys622516123** [Ekey/LA.NPK.Tool#2]
How to use？

**Comment by Ekey** [comment]
You can check usage here > https://github.com/Ekey/LA.NPK.Tool/releases

**Comment by Ruslan16022** [comment]
> You can check usage here > https://github.com/Ekey/LA.NPK.Tool/releases

It's possible to decrypt nxs files? And 2ns question. What's magic number have npk file from LA?

**Comment by Ekey** [comment]
> It's possible to decrypt nxs files?

Scripts automatically [will be decrypted](https://github.com/Ekey/LA.NPK.Tool/blob/main/LA.Unpacker/LA.Unpacker/FileSystem/Package/NpkUnpack.cs#L93) while unpack files.

> What's magic number have npk file from LA?

[You mean this?](https://github.com/Ekey/LA.NPK.Tool/blob/main/LA.Unpacker/LA.Unpacker/FileSystem/Package/NpkUnpack.cs#L30)

**Comment by Ruslan16022** [comment]
> Scripts automatically [will be decrypted](https://github.com/Ekey/LA.NPK.Tool/blob/main/LA.Unpacker/LA.Unpacker/FileSystem/Package/NpkUnpack.cs#L93) while unpack files.

I wanna get original scripts. It's possible?

**Comment by Ekey** [comment]
> I wanna get original scripts. It's possible?

Yep, if you have decompiler, cuz they compiled into Python bytecode.

**Comment by Ruslan16022** [comment]
> 

No ways I think. Btw how u get filenames and how nxs files look like with encryption??

**Comment by Ekey** [comment]
> Btw how u get filenames

Manually by checking all files with a Hex Editor.
