### ISSUE TITLE
.mesh,.gim,.mtg文件是什么?

### ISSUE THREAD

**Issue by BaiGave** [Ekey/LA.NPK.Tool#3]
I have never seen the formats of .mesh, .gim, and .mtg, how can I convert them into files like fbx, obj?

**Comment by Ekey** [comment]
It would be better if you ask about it on [XenTax](https://forum.xentax.com/viewforum.php?f=16) and [ZenHax](https://zenhax.com/viewforum.php?f=5) forums.
