### ISSUE TITLE
Support for Harry Potter Magic Awakened

### ISSUE THREAD

**Issue by TheAlexLichter** [Ekey/LA.NPK.Tool#4]
Hey! Apparently, `.npk` files from HP Magic Awakened are not detected. Any chance that the tool will support them?

[Link to downloading the game](https://www.harrypottermagicawakened.com/global/).

**Comment by Ekey** [comment]
Hey. This npk uses an unknown compression method, probably it's a modified LZ4.

**Comment by TheAlexLichter** [comment]
Ah, too bad. Thanks a lot for trying 🙏
