### ISSUE TITLE
Identity V support?

### ISSUE THREAD

**Issue by mbs0ft** [Ekey/LA.NPK.Tool#5]
Is it possible to support .npk files from Identity V?

<img width="1211" alt="image" src="https://github.com/Ekey/LA.NPK.Tool/assets/22106304/23607757-b7d2-4276-bfc0-e42dfa7b3ea4">

**Comment by Ekey** [comment]
Try this https://github.com/zhouhang95/neox_tools

**Comment by mbs0ft** [comment]
Yeah, that worked, thanks!
